- id: contributors
  name: contributors
  description: Hook to add a CONTRIBUTORS file to your repo based on git shortlog
  entry: contributors
  language: python

- id: changelog
  name: changelog
  description: Hook to manage change logs based on yaml fragements
  entry: changelog
  language: python
